export default data = {
  key: "rsaban_2022_test_02",
  name: "South Africa vs Bangladesh",
  short_name: "RSA vs BAN",
  sub_title: "2nd Test Match",
  teams: {
    a: {
      key: "rsa",
      code: "RSA",
      name: "South Africa",
      country_code: "ZAF",
    },
    b: {
      key: "ban",
      code: "BAN",
      name: "Bangladesh",
      country_code: "BGD",
    },
  },
  start_at: 1649404800.0,
  venue: {
    key: "c__stadium__st_georges_park_cricket_ground__62a72",
    name: "St George's Park Cricket Ground",
    city: "Port Elizabeth",
    country: {
      short_code: "ZA",
      code: "ZAF",
      name: "South Africa",
      official_name: "Republic of South Africa",
      is_region: false,
    },
  },
  tournament: {
    key: "rsaban_2022",
    name: "Bangladesh tour of South Africa, 2022",
    short_name: "RSA vs BAN",
  },
  association: {
    key: "c__board__icc__c2ab7ee61",
    code: "ICC",
    name: "International Cricket Council",
    country: null,
    parent: null,
  },
  metric_group: "MG100",
  status: "started",
  winner: null,
  messages: [],
  gender: "male",
  sport: "cricket",
  format: "test",
  title:
    "South Africa vs Bangladesh - 2nd Test Match - Bangladesh tour of South Africa, 2022",
  play_status: "in_play",
  start_at_local: 1649412000.0,
  toss: { called: "b", winner: "a", elected: "bat" },
  play: {
    first_batting: "a",
    day_number: 1,
    overs_per_innings: null,
    reduced_overs: null,
    target: null,
    result: null,
    innings_order: ["a_1"],
    innings: {
      b_1: {
        index: "b_1",
        overs: [0, 0],
        is_completed: false,
        score_str: "0/0 in 0.0",
        score: {
          runs: 0,
          balls: 0,
          fours: 0,
          sixes: 0,
          dot_balls: 0,
          run_rate: 0.0,
        },
        wickets: 0,
        extra_runs: {
          extra: 0,
          bye: 0,
          leg_bye: 0,
          wide: 0,
          no_ball: 0,
          penalty: null,
        },
        balls_breakup: {
          balls: 0,
          dot_balls: 0,
          wides: 0,
          no_balls: 0,
        },
        batting_order: [],
        bowling_order: ["kha_ahmed", "meh_hasan", "e_hossain", "t_islam"],
        wicket_order: [],
        partnerships: [],
      },
      a_1: {
        index: "a_1",
        overs: [27, 2],
        is_completed: false,
        score_str: "106/1 in 27.2",
        score: {
          runs: 106,
          balls: 164,
          fours: 16,
          sixes: 0,
          dot_balls: 116,
          run_rate: 3.88,
        },
        wickets: 1,
        extra_runs: {
          extra: 0,
          bye: 0,
          leg_bye: 0,
          wide: 0,
          no_ball: 0,
          penalty: null,
        },
        balls_breakup: {
          balls: 164,
          dot_balls: 116,
          wides: 0,
          no_balls: 0,
        },
        batting_order: ["d_elgar", "s_erwee", "ke_petersen"],
        bowling_order: [],
        wicket_order: ["s_erwee"],
        partnerships: [
          {
            begin_overs: [0, 1],
            end_overs: [11, 6],
            player_a_key: "d_elgar",
            player_a_score: {
              runs: 28,
              balls: 32,
              fours: 4,
              sixes: 0,
            },
            player_b_key: "s_erwee",
            player_b_score: {
              runs: 24,
              balls: 40,
              fours: 4,
              sixes: 0,
            },
            score: {
              runs: 52,
              balls: 72,
              fours: 8,
              sixes: 0,
              run_rate: 4.33,
            },
            is_completed: true,
          },
          {
            begin_overs: [12, 1],
            end_overs: [27, 2],
            player_a_key: "d_elgar",
            player_a_score: {
              runs: 31,
              balls: 45,
              fours: 5,
              sixes: 0,
            },
            player_b_key: "ke_petersen",
            player_b_score: {
              runs: 23,
              balls: 47,
              fours: 3,
              sixes: 0,
            },
            score: {
              runs: 54,
              balls: 92,
              fours: 8,
              sixes: 0,
              run_rate: 3.52,
            },
            is_completed: false,
          },
        ],
      },
    },
    live: {
      innings: "a_1",
      batting_team: "a",
      bowling_team: "b",
      last_ball_key: "bcbaef75-556e-4c15-928e-e1db268a6a9a",
      striker_key: "ke_petersen",
      non_striker_key: "d_elgar",
      bowler_key: "meh_hasan",
      match_break: null,
      score: {
        runs: 106,
        balls: 164,
        wickets: 1,
        run_rate: 3.88,
        title: "106/1 in 27.2",
        overs: [27, 2],
        msg_lead_by: null,
        msg_trail_by: null,
      },
      required_score: null,
      recent_overs: [
        {
          overnumber: 28,
          ball_keys: [
            "4a7804ee-d3e5-41aa-a920-7129374a44ad",
            "bcbaef75-556e-4c15-928e-e1db268a6a9a",
          ],
        },
        {
          overnumber: 27,
          ball_keys: [
            "0e77e958-f533-4879-ada0-54c6c8605849",
            "4a734b6c-9cab-42eb-8912-d8490203cdd9",
            "c0f80663-bb65-4dc1-b205-4ea8618eeeac",
            "d7a162ec-21a7-48cf-8bb5-224018756248",
            "4784fd6b-9117-4953-9db7-ad64149caf6b",
            "4cdd106c-2be0-4a61-9ba6-de35bd6f8bde",
          ],
        },
        {
          overnumber: 26,
          ball_keys: [
            "678054cd-6b9b-4ab8-905e-dc18251e112f",
            "cb787925-0ea2-4212-92aa-9af35ced05d0",
            "aadb8711-e047-4399-a2d6-4d91b612686b",
            "d94795ae-ff79-4ded-bb23-9c54dd6758ff",
            "78e49d3c-62c8-4683-831c-f88aaa32538b",
            "c343f833-4376-4a07-ae74-1e1e862e856b",
          ],
        },
      ],
      recent_overs_repr: [
        { overnumber: 28, ball_repr: ["r0", "r1"] },
        {
          overnumber: 27,
          ball_repr: ["r0", "r0", "r0", "r0", "r0", "r0"],
        },
        {
          overnumber: 26,
          ball_repr: ["b4", "r0", "b4", "r1", "r0", "r0"],
        },
      ],
      recent_players: {
        striker: {
          key: "ke_petersen",
          name: "Keegan Petersen",
          stats: {
            runs: 23,
            balls: 47,
            fours: 3,
            sixes: 0,
            dot_balls: 37,
            strike_rate: 48.94,
          },
        },
        non_striker: {
          key: "d_elgar",
          name: "Dean Elgar",
          stats: {
            runs: 59,
            balls: 77,
            fours: 9,
            sixes: 0,
            dot_balls: 50,
            strike_rate: 76.62,
          },
        },
        bowler: {
          key: "meh_hasan",
          name: "Mehidy Hasan",
          stats: {
            balls: 38,
            runs: 31,
            economy: 4.89,
            extras: 0,
            wickets: 0,
            maiden_overs: 0,
            overs: [6, 2],
            balls_breakup: {
              dot_balls: 25,
              wides: 0,
              no_balls: 0,
              fours: 5,
              sixes: 0,
            },
          },
        },
        prev_over_bowler: {
          key: "kha_ahmed",
          name: "Khaled Ahmed",
          stats: {
            balls: 54,
            runs: 38,
            economy: 4.22,
            extras: 0,
            wickets: 1,
            maiden_overs: 1,
            overs: [9, 0],
            balls_breakup: {
              dot_balls: 38,
              wides: 0,
              no_balls: 0,
              fours: 6,
              sixes: 0,
            },
          },
        },
      },
    },
    related_balls: {
      "4cdd106c-2be0-4a61-9ba6-de35bd6f8bde": {
        key: "4cdd106c-2be0-4a61-9ba6-de35bd6f8bde",
        ball_type: "normal",
        batting_team: "a",
        comment: "Taijul Islam to Keegan Petersen: No runs.",
        innings: "a_1",
        overs: [26, 6],
        batsman: {
          player_key: "ke_petersen",
          ball_count: 1,
          runs: 0,
          is_dot_ball: true,
          is_four: false,
          is_six: false,
        },
        bowler: {
          player_key: "t_islam",
          ball_count: 1,
          runs: 0,
          extras: 0,
          is_wicket: false,
        },
        team_score: {
          ball_count: 1,
          runs: 0,
          extras: 0,
          is_wicket: false,
        },
        fielders: [],
        wicket: null,
        non_striker_key: "d_elgar",
        entry_time: 1649411843.318,
      },
      "678054cd-6b9b-4ab8-905e-dc18251e112f": {
        key: "678054cd-6b9b-4ab8-905e-dc18251e112f",
        ball_type: "normal",
        batting_team: "a",
        comment: "Khaled Ahmed to Keegan Petersen: <b>FOUR</b>.",
        innings: "a_1",
        overs: [25, 1],
        batsman: {
          player_key: "ke_petersen",
          ball_count: 1,
          runs: 4,
          is_dot_ball: false,
          is_four: true,
          is_six: false,
        },
        bowler: {
          player_key: "kha_ahmed",
          ball_count: 1,
          runs: 4,
          extras: 0,
          is_wicket: false,
        },
        team_score: {
          ball_count: 1,
          runs: 4,
          extras: 0,
          is_wicket: false,
        },
        fielders: [],
        wicket: null,
        non_striker_key: "d_elgar",
        entry_time: 1649411464.568,
      },
      "4a7804ee-d3e5-41aa-a920-7129374a44ad": {
        key: "4a7804ee-d3e5-41aa-a920-7129374a44ad",
        ball_type: "normal",
        batting_team: "a",
        comment: "Mehidy Hasan to Dean Elgar: No runs.",
        innings: "a_1",
        overs: [27, 1],
        batsman: {
          player_key: "d_elgar",
          ball_count: 1,
          runs: 0,
          is_dot_ball: true,
          is_four: false,
          is_six: false,
        },
        bowler: {
          player_key: "meh_hasan",
          ball_count: 1,
          runs: 0,
          extras: 0,
          is_wicket: false,
        },
        team_score: {
          ball_count: 1,
          runs: 0,
          extras: 0,
          is_wicket: false,
        },
        fielders: [],
        wicket: null,
        non_striker_key: "ke_petersen",
        entry_time: 1649411915.089,
      },
      "c343f833-4376-4a07-ae74-1e1e862e856b": {
        key: "c343f833-4376-4a07-ae74-1e1e862e856b",
        ball_type: "normal",
        batting_team: "a",
        comment: "Khaled Ahmed to Dean Elgar: No runs.",
        innings: "a_1",
        overs: [25, 6],
        batsman: {
          player_key: "d_elgar",
          ball_count: 1,
          runs: 0,
          is_dot_ball: true,
          is_four: false,
          is_six: false,
        },
        bowler: {
          player_key: "kha_ahmed",
          ball_count: 1,
          runs: 0,
          extras: 0,
          is_wicket: false,
        },
        team_score: {
          ball_count: 1,
          runs: 0,
          extras: 0,
          is_wicket: false,
        },
        fielders: [],
        wicket: null,
        non_striker_key: "ke_petersen",
        entry_time: 1649411716.703,
      },
      "aadb8711-e047-4399-a2d6-4d91b612686b": {
        key: "aadb8711-e047-4399-a2d6-4d91b612686b",
        ball_type: "normal",
        batting_team: "a",
        comment: "Khaled Ahmed to Keegan Petersen: <b>FOUR</b>.",
        innings: "a_1",
        overs: [25, 3],
        batsman: {
          player_key: "ke_petersen",
          ball_count: 1,
          runs: 4,
          is_dot_ball: false,
          is_four: true,
          is_six: false,
        },
        bowler: {
          player_key: "kha_ahmed",
          ball_count: 1,
          runs: 4,
          extras: 0,
          is_wicket: false,
        },
        team_score: {
          ball_count: 1,
          runs: 4,
          extras: 0,
          is_wicket: false,
        },
        fielders: [],
        wicket: null,
        non_striker_key: "d_elgar",
        entry_time: 1649411539.996,
      },
      "0e77e958-f533-4879-ada0-54c6c8605849": {
        key: "0e77e958-f533-4879-ada0-54c6c8605849",
        ball_type: "normal",
        batting_team: "a",
        comment: "Taijul Islam to Keegan Petersen: No runs.",
        innings: "a_1",
        overs: [26, 1],
        batsman: {
          player_key: "ke_petersen",
          ball_count: 1,
          runs: 0,
          is_dot_ball: true,
          is_four: false,
          is_six: false,
        },
        bowler: {
          player_key: "t_islam",
          ball_count: 1,
          runs: 0,
          extras: 0,
          is_wicket: false,
        },
        team_score: {
          ball_count: 1,
          runs: 0,
          extras: 0,
          is_wicket: false,
        },
        fielders: [],
        wicket: null,
        non_striker_key: "d_elgar",
        entry_time: 1649411778.48,
      },
      "78e49d3c-62c8-4683-831c-f88aaa32538b": {
        key: "78e49d3c-62c8-4683-831c-f88aaa32538b",
        ball_type: "normal",
        batting_team: "a",
        comment: "Khaled Ahmed to Dean Elgar: No runs.",
        innings: "a_1",
        overs: [25, 5],
        batsman: {
          player_key: "d_elgar",
          ball_count: 1,
          runs: 0,
          is_dot_ball: true,
          is_four: false,
          is_six: false,
        },
        bowler: {
          player_key: "kha_ahmed",
          ball_count: 1,
          runs: 0,
          extras: 0,
          is_wicket: false,
        },
        team_score: {
          ball_count: 1,
          runs: 0,
          extras: 0,
          is_wicket: false,
        },
        fielders: [],
        wicket: null,
        non_striker_key: "ke_petersen",
        entry_time: 1649411645.192,
      },
      "4a734b6c-9cab-42eb-8912-d8490203cdd9": {
        key: "4a734b6c-9cab-42eb-8912-d8490203cdd9",
        ball_type: "normal",
        batting_team: "a",
        comment: "Taijul Islam to Keegan Petersen: No runs.",
        innings: "a_1",
        overs: [26, 2],
        batsman: {
          player_key: "ke_petersen",
          ball_count: 1,
          runs: 0,
          is_dot_ball: true,
          is_four: false,
          is_six: false,
        },
        bowler: {
          player_key: "t_islam",
          ball_count: 1,
          runs: 0,
          extras: 0,
          is_wicket: false,
        },
        team_score: {
          ball_count: 1,
          runs: 0,
          extras: 0,
          is_wicket: false,
        },
        fielders: [],
        wicket: null,
        non_striker_key: "d_elgar",
        entry_time: 1649411783.796,
      },
      "bcbaef75-556e-4c15-928e-e1db268a6a9a": {
        key: "bcbaef75-556e-4c15-928e-e1db268a6a9a",
        ball_type: "normal",
        batting_team: "a",
        comment: "Mehidy Hasan to Dean Elgar: 1 run.",
        innings: "a_1",
        overs: [27, 2],
        batsman: {
          player_key: "d_elgar",
          ball_count: 1,
          runs: 1,
          is_dot_ball: false,
          is_four: false,
          is_six: false,
        },
        bowler: {
          player_key: "meh_hasan",
          ball_count: 1,
          runs: 1,
          extras: 0,
          is_wicket: false,
        },
        team_score: {
          ball_count: 1,
          runs: 1,
          extras: 0,
          is_wicket: false,
        },
        fielders: [],
        wicket: null,
        non_striker_key: "ke_petersen",
        entry_time: 1649411924.569,
      },
      "c0f80663-bb65-4dc1-b205-4ea8618eeeac": {
        key: "c0f80663-bb65-4dc1-b205-4ea8618eeeac",
        ball_type: "normal",
        batting_team: "a",
        comment: "Taijul Islam to Keegan Petersen: No runs.",
        innings: "a_1",
        overs: [26, 3],
        batsman: {
          player_key: "ke_petersen",
          ball_count: 1,
          runs: 0,
          is_dot_ball: true,
          is_four: false,
          is_six: false,
        },
        bowler: {
          player_key: "t_islam",
          ball_count: 1,
          runs: 0,
          extras: 0,
          is_wicket: false,
        },
        team_score: {
          ball_count: 1,
          runs: 0,
          extras: 0,
          is_wicket: false,
        },
        fielders: [],
        wicket: null,
        non_striker_key: "d_elgar",
        entry_time: 1649411801.542,
      },
      "cb787925-0ea2-4212-92aa-9af35ced05d0": {
        key: "cb787925-0ea2-4212-92aa-9af35ced05d0",
        ball_type: "normal",
        batting_team: "a",
        comment: "Khaled Ahmed to Keegan Petersen: No runs.",
        innings: "a_1",
        overs: [25, 2],
        batsman: {
          player_key: "ke_petersen",
          ball_count: 1,
          runs: 0,
          is_dot_ball: true,
          is_four: false,
          is_six: false,
        },
        bowler: {
          player_key: "kha_ahmed",
          ball_count: 1,
          runs: 0,
          extras: 0,
          is_wicket: false,
        },
        team_score: {
          ball_count: 1,
          runs: 0,
          extras: 0,
          is_wicket: false,
        },
        fielders: [],
        wicket: null,
        non_striker_key: "d_elgar",
        entry_time: 1649411487.179,
      },
      "d94795ae-ff79-4ded-bb23-9c54dd6758ff": {
        key: "d94795ae-ff79-4ded-bb23-9c54dd6758ff",
        ball_type: "normal",
        batting_team: "a",
        comment: "Khaled Ahmed to Keegan Petersen: 1 run.",
        innings: "a_1",
        overs: [25, 4],
        batsman: {
          player_key: "ke_petersen",
          ball_count: 1,
          runs: 1,
          is_dot_ball: false,
          is_four: false,
          is_six: false,
        },
        bowler: {
          player_key: "kha_ahmed",
          ball_count: 1,
          runs: 1,
          extras: 0,
          is_wicket: false,
        },
        team_score: {
          ball_count: 1,
          runs: 1,
          extras: 0,
          is_wicket: false,
        },
        fielders: [],
        wicket: null,
        non_striker_key: "d_elgar",
        entry_time: 1649411600.993,
      },
      "4784fd6b-9117-4953-9db7-ad64149caf6b": {
        key: "4784fd6b-9117-4953-9db7-ad64149caf6b",
        ball_type: "normal",
        batting_team: "a",
        comment: "Taijul Islam to Keegan Petersen: No runs.",
        innings: "a_1",
        overs: [26, 5],
        batsman: {
          player_key: "ke_petersen",
          ball_count: 1,
          runs: 0,
          is_dot_ball: true,
          is_four: false,
          is_six: false,
        },
        bowler: {
          player_key: "t_islam",
          ball_count: 1,
          runs: 0,
          extras: 0,
          is_wicket: false,
        },
        team_score: {
          ball_count: 1,
          runs: 0,
          extras: 0,
          is_wicket: false,
        },
        fielders: [],
        wicket: null,
        non_striker_key: "d_elgar",
        entry_time: 1649411828.969,
      },
      "d7a162ec-21a7-48cf-8bb5-224018756248": {
        key: "d7a162ec-21a7-48cf-8bb5-224018756248",
        ball_type: "normal",
        batting_team: "a",
        comment: "Taijul Islam to Keegan Petersen: No runs.",
        innings: "a_1",
        overs: [26, 4],
        batsman: {
          player_key: "ke_petersen",
          ball_count: 1,
          runs: 0,
          is_dot_ball: true,
          is_four: false,
          is_six: false,
        },
        bowler: {
          player_key: "t_islam",
          ball_count: 1,
          runs: 0,
          extras: 0,
          is_wicket: false,
        },
        team_score: {
          ball_count: 1,
          runs: 0,
          extras: 0,
          is_wicket: false,
        },
        fielders: [],
        wicket: null,
        non_striker_key: "d_elgar",
        entry_time: 1649411822.596,
      },
      "056dcb1d-52bd-4d89-9035-08e33cbad20a": {
        key: "056dcb1d-52bd-4d89-9035-08e33cbad20a",
        ball_type: "normal",
        batting_team: "a",
        comment:
          "Khaled Ahmed to Sarel Erwee: <b>Wicket!</b>, Caught by . No runs.",
        innings: "a_1",
        overs: [11, 6],
        batsman: {
          player_key: "s_erwee",
          ball_count: 1,
          runs: 0,
          is_dot_ball: true,
          is_four: false,
          is_six: false,
        },
        bowler: {
          player_key: "kha_ahmed",
          ball_count: 1,
          runs: 0,
          extras: 0,
          is_wicket: true,
        },
        team_score: {
          ball_count: 1,
          runs: 0,
          extras: 0,
          is_wicket: true,
        },
        fielders: [
          {
            player_key: "l_das",
            is_run_out: false,
            is_stumps: false,
            is_catch: true,
            is_assists: false,
          },
        ],
        wicket: { player_key: "s_erwee", wicket_type: "caught" },
        non_striker_key: "d_elgar",
        entry_time: 1649408182.13,
      },
    },
  },
  players: {
    ke_petersen: {
      player: {
        key: "ke_petersen",
        name: "Keegan Petersen",
        jersey_name: "Keegan Petersen",
        legal_name: "Keegan Petersen",
        gender: "male",
        nationality: {
          short_code: "ZA",
          code: "ZAF",
          name: "South Africa",
          official_name: "Republic of South Africa",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "batsman",
        roles: ["batsman"],
        batting_style: "right_hand",
        bowling_style: {
          arm: "right_arm",
          pace: "slow",
          bowling_type: "leg_break",
        },
        skills: ["bat"],
      },
      score: {
        1: {
          batting: {
            score: {
              runs: 23,
              balls: 47,
              fours: 3,
              sixes: 0,
              dot_balls: 37,
              strike_rate: 48.94,
            },
            dismissal: null,
          },
          bowling: null,
          fielding: null,
        },
      },
    },
    e_hossain: {
      player: {
        key: "e_hossain",
        name: "Ebadot Hossain",
        jersey_name: "Ebadot Hossain",
        legal_name: "Ebadot Hossain",
        gender: "male",
        nationality: {
          short_code: "BD",
          code: "BGD",
          name: "Bangladesh",
          official_name: "People's Republic of Bangladesh",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "bowler",
        roles: ["bowler"],
        batting_style: "right_hand",
        bowling_style: {
          arm: "right_arm",
          pace: "medium",
          bowling_type: null,
        },
        skills: ["bowl"],
      },
      score: {
        1: {
          batting: null,
          bowling: {
            score: {
              balls: 42,
              runs: 28,
              economy: 4.0,
              extras: 0,
              wickets: 0,
              maiden_overs: 0,
              overs: [7, 0],
              balls_breakup: {
                dot_balls: 28,
                wides: 0,
                no_balls: 0,
                fours: 4,
                sixes: 0,
              },
            },
          },
          fielding: null,
        },
      },
    },
    l_das: {
      player: {
        key: "l_das",
        name: "Liton Das",
        jersey_name: "Liton Das",
        legal_name: "Liton Das",
        gender: "male",
        nationality: {
          short_code: "BD",
          code: "BGD",
          name: "Bangladesh",
          official_name: "People's Republic of Bangladesh",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "keeper",
        roles: ["keeper"],
        batting_style: "right_hand",
        bowling_style: null,
        skills: ["keep", "bat"],
      },
      score: {
        1: {
          batting: null,
          bowling: null,
          fielding: { catches: 1, stumpings: 0, runouts: 0 },
        },
      },
    },
    du_oliver: {
      player: {
        key: "du_oliver",
        name: "Duanne Olivier",
        jersey_name: "Duanne Olivier",
        legal_name: "Duanne Olivier",
        gender: "male",
        nationality: {
          short_code: "ZA",
          code: "ZAF",
          name: "South Africa",
          official_name: "Republic of South Africa",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "bowler",
        roles: ["bowler"],
        batting_style: "right_hand",
        bowling_style: {
          arm: "right_arm",
          pace: "medium_fast",
          bowling_type: null,
        },
        skills: ["bowl"],
      },
      score: { 1: { batting: null, bowling: null, fielding: null } },
    },
    c__player__mahmudul_hasan_joy__ddd88: {
      player: {
        key: "c__player__mahmudul_hasan_joy__ddd88",
        name: "Mahmudul Hasan Joy",
        jersey_name: "Mahmudul Hasan Joy",
        legal_name: "Mahmudul Hasan Joy",
        gender: "male",
        nationality: {
          short_code: "BD",
          code: "BGD",
          name: "Bangladesh",
          official_name: "People's Republic of Bangladesh",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "batsman",
        roles: ["batsman"],
        batting_style: "right_hand",
        bowling_style: {
          arm: "right_arm",
          pace: "slow",
          bowling_type: null,
        },
        skills: ["bat"],
      },
      score: { 1: { batting: null, bowling: null, fielding: null } },
    },
    a_jayed: {
      player: {
        key: "a_jayed",
        name: "Abu Jayed",
        jersey_name: "Abu Jayed",
        legal_name: "Abu Jayed",
        gender: "male",
        nationality: {
          short_code: "BD",
          code: "BGD",
          name: "Bangladesh",
          official_name: "People's Republic of Bangladesh",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "bowler",
        roles: ["bowler"],
        batting_style: "right_hand",
        bowling_style: {
          arm: "right_arm",
          pace: "fast_medium",
          bowling_type: null,
        },
        skills: ["bowl"],
      },
      score: { 1: { batting: null, bowling: null, fielding: null } },
    },
    sh_islam: {
      player: {
        key: "sh_islam",
        name: "Shadman Islam",
        jersey_name: "Shadman Islam",
        legal_name: "Shadman Islam",
        gender: "male",
        nationality: {
          short_code: "BD",
          code: "BGD",
          name: "Bangladesh",
          official_name: "People's Republic of Bangladesh",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "batsman",
        roles: ["batsman"],
        batting_style: "left_hand",
        bowling_style: {
          arm: "left_arm",
          pace: "slow",
          bowling_type: "orthodox",
        },
        skills: ["bat"],
      },
      score: { 1: { batting: null, bowling: null, fielding: null } },
    },
    ta_ahmed: {
      player: {
        key: "ta_ahmed",
        name: "Taskin Ahmed",
        jersey_name: "Taskin Ahmed",
        legal_name: "Taskin Ahmed",
        gender: "male",
        nationality: {
          short_code: "BD",
          code: "BGD",
          name: "Bangladesh",
          official_name: "People's Republic of Bangladesh",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "bowler",
        roles: ["bowler"],
        batting_style: "left_hand",
        bowling_style: {
          arm: "right_arm",
          pace: "fast",
          bowling_type: null,
        },
        skills: ["bowl"],
      },
      score: { 1: { batting: null, bowling: null, fielding: null } },
    },
    m_rahim: {
      player: {
        key: "m_rahim",
        name: "Mushfiqur Rahim",
        jersey_name: "Mushfiqur Rahim",
        legal_name: "Mushfiqur Rahim",
        gender: "male",
        nationality: {
          short_code: "BD",
          code: "BGD",
          name: "Bangladesh",
          official_name: "People's Republic of Bangladesh",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "keeper",
        roles: ["keeper"],
        batting_style: "right_hand",
        bowling_style: null,
        skills: ["keep", "bat"],
      },
      score: { 1: { batting: null, bowling: null, fielding: null } },
    },
    wia_mulder: {
      player: {
        key: "wia_mulder",
        name: "Wiaan Mulder",
        jersey_name: "Wiaan Mulder",
        legal_name: "Wiaan Mulder",
        gender: "male",
        nationality: {
          short_code: "ZA",
          code: "ZAF",
          name: "South Africa",
          official_name: "Republic of South Africa",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "all_rounder",
        roles: ["all_rounder"],
        batting_style: "right_hand",
        bowling_style: {
          arm: "right_arm",
          pace: "medium",
          bowling_type: null,
        },
        skills: ["bowl", "bat"],
      },
      score: { 1: { batting: null, bowling: null, fielding: null } },
    },
    sha_islam: {
      player: {
        key: "sha_islam",
        name: "Shahidul Islam",
        jersey_name: "Shahidul Islam",
        legal_name: "Shahidul Islam",
        gender: "male",
        nationality: {
          short_code: "BD",
          code: "BGD",
          name: "Bangladesh",
          official_name: "People's Republic of Bangladesh",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "bowler",
        roles: ["bowler"],
        batting_style: "right_hand",
        bowling_style: {
          arm: "right_arm",
          pace: "medium",
          bowling_type: null,
        },
        skills: ["bowl"],
      },
      score: { 1: { batting: null, bowling: null, fielding: null } },
    },
    n_hossain: {
      player: {
        key: "n_hossain",
        name: "Najmul Hossain Shanto",
        jersey_name: "Najmul Hossain Shanto",
        legal_name: "Najmul Hossain Shanto",
        gender: "male",
        nationality: {
          short_code: "BD",
          code: "BGD",
          name: "Bangladesh",
          official_name: "People's Republic of Bangladesh",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "batsman",
        roles: ["batsman"],
        batting_style: "left_hand",
        bowling_style: {
          arm: "right_arm",
          pace: "slow",
          bowling_type: null,
        },
        skills: ["bat"],
      },
      score: { 1: { batting: null, bowling: null, fielding: null } },
    },
    r_rickelton: {
      player: {
        key: "r_rickelton",
        name: "Ryan Rickelton",
        jersey_name: "Ryan Rickelton",
        legal_name: "Ryan Rickelton",
        gender: "male",
        nationality: {
          short_code: "ZA",
          code: "ZAF",
          name: "South Africa",
          official_name: "Republic of South Africa",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "keeper",
        roles: ["keeper"],
        batting_style: "left_hand",
        bowling_style: null,
        skills: ["keep", "bat"],
      },
      score: { 1: { batting: null, bowling: null, fielding: null } },
    },
    t_bavuma: {
      player: {
        key: "t_bavuma",
        name: "Temba Bavuma",
        jersey_name: "Temba Bavuma",
        legal_name: "Temba Bavuma",
        gender: "male",
        nationality: {
          short_code: "ZA",
          code: "ZAF",
          name: "South Africa",
          official_name: "Republic of South Africa",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "batsman",
        roles: ["batsman"],
        batting_style: "right_hand",
        bowling_style: {
          arm: "right_arm",
          pace: "medium",
          bowling_type: null,
        },
        skills: ["bat"],
      },
      score: { 1: { batting: null, bowling: null, fielding: null } },
    },
    kha_ahmed: {
      player: {
        key: "kha_ahmed",
        name: "Khaled Ahmed",
        jersey_name: "Khaled Ahmed",
        legal_name: "Khaled Ahmed",
        gender: "male",
        nationality: {
          short_code: "BD",
          code: "BGD",
          name: "Bangladesh",
          official_name: "People's Republic of Bangladesh",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "bowler",
        roles: ["bowler"],
        batting_style: "right_hand",
        bowling_style: {
          arm: "right_arm",
          pace: "medium",
          bowling_type: null,
        },
        skills: ["bowl"],
      },
      score: {
        1: {
          batting: null,
          bowling: {
            score: {
              balls: 54,
              runs: 38,
              economy: 4.22,
              extras: 0,
              wickets: 1,
              maiden_overs: 1,
              overs: [9, 0],
              balls_breakup: {
                dot_balls: 38,
                wides: 0,
                no_balls: 0,
                fours: 6,
                sixes: 0,
              },
            },
          },
          fielding: null,
        },
      },
    },
    ya_ali: {
      player: {
        key: "ya_ali",
        name: "Yasir Ali Choudhary",
        jersey_name: "Yasir Ali Choudhary",
        legal_name: "Yasir Ali Choudhary",
        gender: "male",
        nationality: {
          short_code: "BD",
          code: "BGD",
          name: "Bangladesh",
          official_name: "People's Republic of Bangladesh",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "batsman",
        roles: ["batsman"],
        batting_style: "right_hand",
        bowling_style: {
          arm: "right_arm",
          pace: "fast_medium",
          bowling_type: null,
        },
        skills: ["bat"],
      },
      score: { 1: { batting: null, bowling: null, fielding: null } },
    },
    t_islam: {
      player: {
        key: "t_islam",
        name: "Taijul Islam",
        jersey_name: "Taijul Islam",
        legal_name: "Taijul Islam",
        gender: "male",
        nationality: {
          short_code: "BD",
          code: "BGD",
          name: "Bangladesh",
          official_name: "People's Republic of Bangladesh",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "bowler",
        roles: ["bowler"],
        batting_style: "left_hand",
        bowling_style: null,
        skills: ["bowl"],
      },
      score: {
        1: {
          batting: null,
          bowling: {
            score: {
              balls: 30,
              runs: 9,
              economy: 1.8,
              extras: 0,
              wickets: 0,
              maiden_overs: 1,
              overs: [5, 0],
              balls_breakup: {
                dot_balls: 25,
                wides: 0,
                no_balls: 0,
                fours: 1,
                sixes: 0,
              },
            },
          },
          fielding: null,
        },
      },
    },
    k_maharaj: {
      player: {
        key: "k_maharaj",
        name: "K Maharaj",
        jersey_name: "K Maharaj",
        legal_name: "Keshav Maharaj",
        gender: "male",
        nationality: {
          short_code: "ZA",
          code: "ZAF",
          name: "South Africa",
          official_name: "Republic of South Africa",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "bowler",
        roles: ["bowler"],
        batting_style: "right_hand",
        bowling_style: {
          arm: "left_arm",
          pace: "slow",
          bowling_type: "orthodox",
        },
        skills: ["bowl"],
      },
      score: { 1: { batting: null, bowling: null, fielding: null } },
    },
    s_erwee: {
      player: {
        key: "s_erwee",
        name: "Sarel Erwee",
        jersey_name: "Sarel Erwee",
        legal_name: "Sarel Erwee",
        gender: "male",
        nationality: {
          short_code: "ZA",
          code: "ZAF",
          name: "South Africa",
          official_name: "Republic of South Africa",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "batsman",
        roles: ["batsman"],
        batting_style: "left_hand",
        bowling_style: {
          arm: "right_arm",
          pace: "slow",
          bowling_type: null,
        },
        skills: ["bat"],
      },
      score: {
        1: {
          batting: {
            score: {
              runs: 24,
              balls: 40,
              fours: 4,
              sixes: 0,
              dot_balls: 29,
              strike_rate: 60.0,
            },
            dismissal: {
              overs: [11, 6],
              team_runs: 52,
              wicket_number: 1,
              msg: "c Liton Das b Khaled Ahmed",
              ball_key: "056dcb1d-52bd-4d89-9035-08e33cbad20a",
            },
          },
          bowling: null,
          fielding: null,
        },
      },
    },
    liz_williams: {
      player: {
        key: "liz_williams",
        name: "Lizaad Williams",
        jersey_name: "Lizaad Williams",
        legal_name: "Lizaad Williams",
        gender: "male",
        nationality: {
          short_code: "ZA",
          code: "ZAF",
          name: "South Africa",
          official_name: "Republic of South Africa",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "bowler",
        roles: ["bowler"],
        batting_style: "left_hand",
        bowling_style: {
          arm: "right_arm",
          pace: "medium_fast",
          bowling_type: null,
        },
        skills: ["bowl"],
      },
      score: { 1: { batting: null, bowling: null, fielding: null } },
    },
    m_haque: {
      player: {
        key: "m_haque",
        name: "Mominul Haque",
        jersey_name: "Mominul Haque",
        legal_name: "Mominul Haque",
        gender: "male",
        nationality: {
          short_code: "BD",
          code: "BGD",
          name: "Bangladesh",
          official_name: "People's Republic of Bangladesh",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "all_rounder",
        roles: ["all_rounder"],
        batting_style: "left_hand",
        bowling_style: {
          arm: "left_arm",
          pace: "slow",
          bowling_type: null,
        },
        skills: ["bat"],
      },
      score: { 1: { batting: null, bowling: null, fielding: null } },
    },
    lut_sipamla: {
      player: {
        key: "lut_sipamla",
        name: "Lutho Sipamla",
        jersey_name: "Lutho Sipamla",
        legal_name: "Lutho Sipamla",
        gender: "male",
        nationality: {
          short_code: "ZA",
          code: "ZAF",
          name: "South Africa",
          official_name: "Republic of South Africa",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "bowler",
        roles: ["bowler"],
        batting_style: "right_hand",
        bowling_style: {
          arm: "right_arm",
          pace: "fast",
          bowling_type: null,
        },
        skills: ["bowl"],
      },
      score: { 1: { batting: null, bowling: null, fielding: null } },
    },
    d_dupavillon: {
      player: {
        key: "d_dupavillon",
        name: "D Dupavillon",
        jersey_name: "D Dupavillon",
        legal_name: "Daryn Dupavillon",
        gender: "male",
        nationality: {
          short_code: "ZA",
          code: "ZAF",
          name: "South Africa",
          official_name: "Republic of South Africa",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "bowler",
        roles: ["bowler"],
        batting_style: "right_hand",
        bowling_style: {
          arm: "right_arm",
          pace: "fast",
          bowling_type: null,
        },
        skills: ["bowl"],
      },
      score: { 1: { batting: null, bowling: null, fielding: null } },
    },
    t_iqbal: {
      player: {
        key: "t_iqbal",
        name: "Tamim Iqbal",
        jersey_name: "Tamim Iqbal",
        legal_name: "Tamim Iqbal",
        gender: "male",
        nationality: {
          short_code: "BD",
          code: "BGD",
          name: "Bangladesh",
          official_name: "People's Republic of Bangladesh",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "batsman",
        roles: ["batsman"],
        batting_style: "left_hand",
        bowling_style: {
          arm: "right_arm",
          pace: "slow",
          bowling_type: null,
        },
        skills: ["bat"],
      },
      score: { 1: { batting: null, bowling: null, fielding: null } },
    },
    nu_hasan: {
      player: {
        key: "nu_hasan",
        name: "Nurul Hasan",
        jersey_name: "Nurul Hasan",
        legal_name: "Nurul Hasan",
        gender: "male",
        nationality: {
          short_code: "BD",
          code: "BGD",
          name: "Bangladesh",
          official_name: "People's Republic of Bangladesh",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "keeper",
        roles: ["keeper"],
        batting_style: "right_hand",
        bowling_style: null,
        skills: ["keep", "bat"],
      },
      score: { 1: { batting: null, bowling: null, fielding: null } },
    },
    s_harmer: {
      player: {
        key: "s_harmer",
        name: "Simon Harmer",
        jersey_name: "Simon Harmer",
        legal_name: "Simon Harmer",
        gender: "male",
        nationality: {
          short_code: "ZA",
          code: "ZAF",
          name: "South Africa",
          official_name: "Republic of South Africa",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "bowler",
        roles: ["bowler"],
        batting_style: "right_hand",
        bowling_style: {
          arm: "right_arm",
          pace: "slow",
          bowling_type: null,
        },
        skills: ["bowl"],
      },
      score: { 1: { batting: null, bowling: null, fielding: null } },
    },
    k_verreynne: {
      player: {
        key: "k_verreynne",
        name: "Kyle Verreynne",
        jersey_name: "Kyle Verreynne",
        legal_name: "Kyle Verreynne",
        gender: "male",
        nationality: {
          short_code: "ZA",
          code: "ZAF",
          name: "South Africa",
          official_name: "Republic of South Africa",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "keeper",
        roles: ["keeper"],
        batting_style: "right_hand",
        bowling_style: {
          arm: "right_arm",
          pace: "slow",
          bowling_type: null,
        },
        skills: ["keep", "bat"],
      },
      score: { 1: { batting: null, bowling: null, fielding: null } },
    },
    c__player__shoriful_islam__57c37: {
      player: {
        key: "c__player__shoriful_islam__57c37",
        name: "Shoriful Islam",
        jersey_name: "Shoriful Islam",
        legal_name: "Shoriful Islam",
        gender: "male",
        nationality: {
          short_code: "BD",
          code: "BGD",
          name: "Bangladesh",
          official_name: "People's Republic of Bangladesh",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "bowler",
        roles: ["bowler"],
        batting_style: "left_hand",
        bowling_style: {
          arm: "left_arm",
          pace: "medium_fast",
          bowling_type: null,
        },
        skills: ["bowl"],
      },
      score: { 1: { batting: null, bowling: null, fielding: null } },
    },
    g_suurmant: {
      player: {
        key: "g_suurmant",
        name: "Glenton Stuurman",
        jersey_name: "Glenton Stuurman",
        legal_name: "Glenton Stuurman",
        gender: "male",
        nationality: {
          short_code: "ZA",
          code: "ZAF",
          name: "South Africa",
          official_name: "Republic of South Africa",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "bowler",
        roles: ["bowler"],
        batting_style: "right_hand",
        bowling_style: {
          arm: "right_arm",
          pace: "medium",
          bowling_type: null,
        },
        skills: ["bowl"],
      },
      score: { 1: { batting: null, bowling: null, fielding: null } },
    },
    ai_hasan: {
      player: {
        key: "ai_hasan",
        name: "Shakib Al Hasan",
        jersey_name: "Shakib Al Hasan",
        legal_name: "Shakib Al Hasan",
        gender: "male",
        nationality: {
          short_code: "BD",
          code: "BGD",
          name: "Bangladesh",
          official_name: "People's Republic of Bangladesh",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "all_rounder",
        roles: ["all_rounder"],
        batting_style: "left_hand",
        bowling_style: {
          arm: "left_arm",
          pace: "slow",
          bowling_type: "orthodox",
        },
        skills: ["bowl", "bat"],
      },
      score: { 1: { batting: null, bowling: null, fielding: null } },
    },
    k_zondo: {
      player: {
        key: "k_zondo",
        name: "Khaya Zondo",
        jersey_name: "Khaya Zondo",
        legal_name: "Khaya Zondo",
        gender: "male",
        nationality: {
          short_code: "ZA",
          code: "ZAF",
          name: "South Africa",
          official_name: "Republic of South Africa",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "batsman",
        roles: ["batsman"],
        batting_style: "right_hand",
        bowling_style: {
          arm: "right_arm",
          pace: "slow",
          bowling_type: null,
        },
        skills: ["bat"],
      },
      score: { 1: { batting: null, bowling: null, fielding: null } },
    },
    d_elgar: {
      player: {
        key: "d_elgar",
        name: "Dean Elgar",
        jersey_name: "Dean Elgar",
        legal_name: "Dean Elgar",
        gender: "male",
        nationality: {
          short_code: "ZA",
          code: "ZAF",
          name: "South Africa",
          official_name: "Republic of South Africa",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "batsman",
        roles: ["batsman"],
        batting_style: "left_hand",
        bowling_style: {
          arm: "left_arm",
          pace: "slow",
          bowling_type: "orthodox",
        },
        skills: ["bat"],
      },
      score: {
        1: {
          batting: {
            score: {
              runs: 59,
              balls: 77,
              fours: 9,
              sixes: 0,
              dot_balls: 50,
              strike_rate: 76.62,
            },
            dismissal: null,
          },
          bowling: null,
          fielding: null,
        },
      },
    },
    meh_hasan: {
      player: {
        key: "meh_hasan",
        name: "Mehidy Hasan",
        jersey_name: "Mehidy Hasan",
        legal_name: "Mehidy Hasan",
        gender: "male",
        nationality: {
          short_code: "BD",
          code: "BGD",
          name: "Bangladesh",
          official_name: "People's Republic of Bangladesh",
          is_region: false,
        },
        date_of_birth: null,
        seasonal_role: "all_rounder",
        roles: ["all_rounder"],
        batting_style: "right_hand",
        bowling_style: {
          arm: "right_arm",
          pace: "slow",
          bowling_type: null,
        },
        skills: ["bowl", "bat"],
      },
      score: {
        1: {
          batting: null,
          bowling: {
            score: {
              balls: 38,
              runs: 31,
              economy: 4.89,
              extras: 0,
              wickets: 0,
              maiden_overs: 0,
              overs: [6, 2],
              balls_breakup: {
                dot_balls: 25,
                wides: 0,
                no_balls: 0,
                fours: 5,
                sixes: 0,
              },
            },
          },
          fielding: null,
        },
      },
    },
  },
  notes: [],
  data_review: {
    schedule: true,
    venue: true,
    result: false,
    pom: false,
    score: false,
    players: true,
    playing_xi: true,
    score_reviewed_ball_index: ["a_1", [27, 2]],
    team_a: true,
    team_b: true,
    good_to_close: false,
    note: null,
  },
  squad: {
    a: {
      player_keys: [
        "r_rickelton",
        "liz_williams",
        "s_harmer",
        "k_verreynne",
        "ke_petersen",
        "g_suurmant",
        "lut_sipamla",
        "k_zondo",
        "du_oliver",
        "d_elgar",
        "d_dupavillon",
        "wia_mulder",
        "k_maharaj",
        "s_erwee",
        "t_bavuma",
      ],
      captain: "d_elgar",
      keeper: "k_verreynne",
      playing_xi: [
        "d_elgar",
        "s_erwee",
        "ke_petersen",
        "t_bavuma",
        "r_rickelton",
        "k_verreynne",
        "wia_mulder",
        "k_maharaj",
        "s_harmer",
        "liz_williams",
        "du_oliver",
      ],
    },
    b: {
      player_keys: [
        "nu_hasan",
        "c__player__shoriful_islam__57c37",
        "e_hossain",
        "m_haque",
        "l_das",
        "kha_ahmed",
        "ai_hasan",
        "t_iqbal",
        "t_islam",
        "ya_ali",
        "c__player__mahmudul_hasan_joy__ddd88",
        "meh_hasan",
        "a_jayed",
        "sh_islam",
        "ta_ahmed",
        "m_rahim",
        "sha_islam",
        "n_hossain",
      ],
      captain: "m_haque",
      keeper: "l_das",
      playing_xi: [
        "t_iqbal",
        "c__player__mahmudul_hasan_joy__ddd88",
        "n_hossain",
        "m_haque",
        "m_rahim",
        "l_das",
        "ya_ali",
        "meh_hasan",
        "kha_ahmed",
        "e_hossain",
        "t_islam",
      ],
    },
  },
  estimated_end_date: 1649782800.0,
  completed_date_approximate: null,
  umpires: {
    match_umpires: null,
    tv_umpires: null,
    reserve_umpires: null,
    match_referee: null,
  },
};
